# Generated by Django 3.0.7 on 2020-06-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
